import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Avatar } from '../components/Avatar';
import { useApp } from '../context/AppContext';
import { RootStackParamList } from '../navigation/RootNavigator';
import { colors, radii } from '../theme';

export function SettingsScreen({ navigation }: NativeStackScreenProps<RootStackParamList>) {
  const { currentUser, settings, setToggle, logout } = useApp();
  const Row = ({ label, onPress }: { label: string; onPress?: () => void }) => <Pressable style={styles.row} onPress={onPress}><Text style={styles.n}>{label}</Text></Pressable>;
  return <ScrollView style={styles.c}><Text style={styles.t}>Settings</Text><View style={styles.profile}><Avatar name={currentUser?.name || 'Me'} /><View><Text style={styles.n}>{currentUser?.name}</Text><Text style={styles.m}>{currentUser?.phone}</Text></View></View><Row label="Account" /><Row label="Privacy" onPress={() => navigation.navigate('Privacy')} /><Row label="Notifications" /><Row label="Chat Theme" onPress={() => navigation.navigate('Theme')} /><Row label="Storage and Data" /><Row label="AI Features" /><Row label="Security" /><Row label="Help and Support" /><View style={styles.card}><Text style={styles.n}>End-to-end encryption</Text><Text style={styles.m}>Messages are secured in transit and at rest-ready architecture.</Text></View><View style={styles.toggle}><Text style={styles.n}>Fingerprint Lock</Text><Switch value={settings.fingerprintLock} onValueChange={(v) => setToggle('fingerprintLock', v)} /></View><View style={styles.toggle}><Text style={styles.n}>Private Vault Chats</Text><Switch value={settings.privateVault} onValueChange={(v) => setToggle('privateVault', v)} /></View><View style={styles.toggle}><Text style={styles.n}>Disappearing Messages</Text><Switch value={settings.disappearingMessages} onValueChange={(v) => setToggle('disappearingMessages', v)} /></View><Text style={[styles.n, { marginTop: 16 }]}>AI Settings</Text><View style={styles.toggle}><Text style={styles.m}>Smart Replies</Text><Switch value={settings.smartReplies} onValueChange={(v) => setToggle('smartReplies', v)} /></View><View style={styles.toggle}><Text style={styles.m}>Auto Translation</Text><Switch value={settings.autoTranslation} onValueChange={(v) => setToggle('autoTranslation', v)} /></View><View style={styles.toggle}><Text style={styles.m}>Spam Detection</Text><Switch value={settings.spamDetection} onValueChange={(v) => setToggle('spamDetection', v)} /></View><View style={styles.toggle}><Text style={styles.m}>Chat Summary</Text><Switch value={settings.chatSummary} onValueChange={(v) => setToggle('chatSummary', v)} /></View><Pressable style={styles.out} onPress={async () => { await logout(); navigation.replace('Login'); }}><Text style={styles.outT}>Logout</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ c: { flex: 1, backgroundColor: colors.background, padding: 14 }, t: { color: colors.text, fontSize: 28, fontWeight: '800', marginBottom: 10 }, profile: { flexDirection: 'row', gap: 12, alignItems: 'center', backgroundColor: colors.card, padding: 12, borderRadius: radii.lg, marginBottom: 10 }, row: { backgroundColor: colors.card, padding: 12, borderRadius: radii.lg, marginBottom: 8 }, n: { color: colors.text, fontWeight: '700' }, m: { color: colors.mutedText }, card: { backgroundColor: '#163046', borderRadius: radii.lg, padding: 12, marginVertical: 10 }, toggle: { backgroundColor: colors.card, padding: 12, borderRadius: radii.lg, marginBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, out: { backgroundColor: colors.danger, borderRadius: radii.lg, padding: 12, alignItems: 'center', marginTop: 8, marginBottom: 120 }, outT: { color: colors.text, fontWeight: '700' } });
