import React from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '../components/Avatar';
import { useApp } from '../context/AppContext';
import { colors, radii } from '../theme';

export function StatusScreen() {
  const { statuses, currentUser } = useApp();
  return <ScrollView style={styles.c}><Text style={styles.t}>Status</Text><View style={styles.card}><Avatar name={currentUser?.name || 'Me'} /><View><Text style={styles.n}>My Status</Text><Text style={styles.m}>Tap to add status</Text></View><Pressable><Text style={styles.add}>+</Text></Pressable></View><Text style={styles.s}>Stories</Text><ScrollView horizontal>{statuses.map((s) => <View style={styles.story} key={s.id}><View style={[styles.ring, s.viewed && { borderColor: colors.border }]}><Avatar name={s.name} size={56} /></View><Text style={styles.sn}>{s.name}</Text></View>)}</ScrollView><Text style={styles.s}>Recent updates</Text><FlatList data={statuses.filter((x) => !x.viewed)} keyExtractor={(x) => x.id} renderItem={({ item }) => <View style={styles.row}><Avatar name={item.name} /><View><Text style={styles.n}>{item.name}</Text><Text style={styles.m}>{item.type} • {item.time}</Text></View></View>} scrollEnabled={false} /><Pressable style={styles.ai}><Text style={styles.aiT}>AI Status Caption Generator</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ c: { flex: 1, backgroundColor: colors.background, padding: 14 }, t: { color: colors.text, fontSize: 28, fontWeight: '800', marginBottom: 10 }, card: { backgroundColor: colors.card, padding: 12, borderRadius: radii.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, n: { color: colors.text, fontWeight: '700' }, m: { color: colors.mutedText }, add: { color: colors.accent, fontSize: 30 }, s: { color: colors.mutedText, marginVertical: 10 }, story: { marginRight: 12, alignItems: 'center' }, ring: { borderWidth: 2, borderColor: colors.secondary, borderRadius: radii.full, padding: 3 }, sn: { color: colors.text, marginTop: 4, fontSize: 12 }, row: { flexDirection: 'row', gap: 12, backgroundColor: colors.card, marginBottom: 8, padding: 10, borderRadius: radii.lg }, ai: { backgroundColor: '#0F3D5D', padding: 12, borderRadius: radii.lg, marginTop: 10, marginBottom: 120 }, aiT: { color: colors.text, fontWeight: '700' } });
